version: "3.8"

services:
  oracledb:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    ports:
      - "1521:1521" # Porta padrão do Oracle
      - "5500:5500" # Porta opcional para APEX
    environment:
      ORACLE_PASSWORD: oracle # Altere conforme necessário
      APP_USER: appuser
      APP_USER_PASSWORD: appuser123
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped

volumes:
  oracle-data:
